spring:
  application:
    name: microservice-customer

  devtools:
    restart:
      enabled: true
  data:
    mongodb:
      uri: mongodb://localhost:27017
      database: db_customer

server:
  port: 8080
  servlet:
    context-path: /customer